# Ref https://docs.docker.com/compose/compose-file/#/version-2
version: '2'

services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/app
      - node_modules:/var/app/node_modules
    ports:
      - 8080:8080
volumes:
  node_modules:
    driver: local