# Ref https://docs.docker.com/compose/compose-file/#/version-2
version: '2'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - .:/var/app
      - node_modules:/var/app/node_modules
volumes:
  node_modules:
    external:
      name: missionpozible_node_modules