# Ref https://docs.docker.com/compose/compose-file/#/version-2
version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/app
      - node_modules:/var/app/node_modules
      - meteor_local:/var/app/.meteor/local
    ports:
      - 3000:3000
      - 3500:3500
    links:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017
  db:
    image: mongo
volumes:
  node_modules:
    driver: local
  meteor_local:
    driver: local